# Generated by Django 5.1 on 2025-05-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citysay', '0002_institution_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='institution',
            field=models.CharField(choices=[('PEDA', 'Colegiul National Pedagogic "Regina Maria" Deva'), ('POLICE', 'Politia Deva'), ('LUCI', 'Primaria Municipiului Deva'), ('ISJ', 'Inspectoratul Scolar Judetean Hunedoara'), ('CJH', 'Consiliul Judetean Hunedoara'), ('NONE', 'None')], max_length=200),
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
    ]
