# Generated by Django 5.1 on 2025-05-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citysay', '0004_institution_poll_institution_alter_user_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
