# Generated by Django 5.1 on 2025-05-26 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citysay', '0005_option_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesization',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sesization',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citysay.institution'),
        ),
    ]
