# Generated by Django 5.2.1 on 2025-05-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citysay', '0006_sesization_date_sesization_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesization',
            name='status',
            field=models.CharField(default='în asteptare...', max_length=10),
            preserve_default=False,
        ),
    ]
