# Generated by Django 5.1 on 2025-05-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citysay', '0007_sesization_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesization',
            name='status',
            field=models.CharField(default='In asteptare', max_length=10),
        ),
    ]
