# Generated by Django 5.1 on 2025-05-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citysay', '0009_alter_sesization_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesization',
            name='status',
            field=models.CharField(default='În Așteptare', max_length=30),
        ),
    ]
